# Copyright (c) Helio Chissini de Castro, 2023. Part of the SW360 Frontend Project.

# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/

# SPDX-License-Identifier: EPL-2.0
# License-Filename: LICENSE

header:
    license:
        spdx-id: EPL-2.0
        copyright-owner: SW360 Frontend Authors
        copyright-year: '2023'
        software-name: sw360-frontend
        pattern: |
            This program and the accompanying materials are made
            available under the terms of the Eclipse Public License 2.0
            which is available at https://www.eclipse.org/legal/epl-2.0/

            SPDX-License-Identifier: EPL-2.0
            License-Filename: LICENSE

    paths:
        - '**'

    paths-ignore:
        - 'node_modulesw'
        - '**/*.md'
        - '**/testdata/**'
        - 'LICENSE'
        - 'NOTICE'
        - '*.code-workspace'
        - '**/*.diff'
        - '**/*.svg'
        - .prettierrc
        - '**/*.json'
        - '**/*.css'
        - .dockerignore
        - .gitignore
        - .husky
        - '.github/**'
        - 'cypress/fixtures/**'
        - "pnpm-lock.yaml"
        - "pnpm-workspace.yaml"

    comment: on-failure

    license-location-threshold: 80

dependency:
    files:
        - package.json
